version: '3'
services:
  web:
    image: node:18
    container_name: node_app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    build: ./
    command: yarn dev



